import Head from "next/head";

import Content from "../components/Content";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Content />
      </main>

      {/* <footer></footer> */}
    </div>
  );
}
